Localised Redirections #49
chinleung/laravel-multilingual-routes pull request #60
Opened 2021-10-18 12:10 UTC by AbdullahFaqeir

- Added ability to redirect localised routes to localised routes.
- Updated min php version to 7.4.
- Code refactor.

2021-10-19 02:36 UTC, chinleung commented
Thanks for the PR @AbdullahFaqeir ! Can you remove PHP 7.3 and lower from the tests please?

2021-10-19 03:20 UTC, AbdullahFaqeir commented
@chinleung Done.

2021-10-19 13:35 UTC, chinleung requested changes
Also, is there any reason why you've changed most of the `==` to `===`?

2021-10-19 13:35 UTC, chinleung commented on src/DetectRequestLocale.php
> +        if (in_array($segment, locales(), false)) {
I don't think we need the `false` here. It's already false by default.

2021-10-19 13:35 UTC, chinleung commented on src/DetectRequestLocale.php
> +use Symfony\Component\HttpFoundation\Request;
Why not `Illuminate\Http\Request` instead?

2021-10-19 13:35 UTC, chinleung commented on src/MultilingualRegistrar.php
> +        )
Can you fix the indentation here please? :)

2021-10-21 14:49 UTC, AbdullahFaqeir commented on src/DetectRequestLocale.php
> +        if (in_array($segment, locales(), false)) {
It should not effect the presses of the package, if you really want to remove it, I remove later today.

2021-10-21 14:49 UTC, AbdullahFaqeir commented on src/DetectRequestLocale.php
> +use Symfony\Component\HttpFoundation\Request;
This is a polymorph type hint

2021-10-21 14:51 UTC, AbdullahFaqeir commented on src/MultilingualRegistrar.php
> +        )
It didn't show any error on the CS checker.

2021-10-22 12:32 UTC, merged